# Generated by Django 4.2.30 on 2026-06-17 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_items_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://img.magnific.com/premium-psd/pizza-slices-burgers-floating-isolated-transparent-background-rounded-by-spices-food_1232930-3777.jpg?semt=ais_hybrid&w=740&q=80', max_length=500),
        ),
        migrations.AlterField(
            model_name='item',
            name='item_desc',
            field=models.CharField(max_length=10000),
        ),
    ]
