# Generated by Django 4.2.30 on 2026-06-26 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_item_item_name_alter_item_item_price'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='item',
            index=models.Index(fields=['user_name', 'item_price'], name='myapp_item_user_na_18bfbe_idx'),
        ),
    ]
